SET FOREIGN_KEY_CHECKS = 0;
USE AttendanceSystem;

TRUNCATE TABLE AttendanceRecords;

TRUNCATE TABLE AttendanceSessions;

TRUNCATE TABLE Enrollments;

TRUNCATE TABLE Classes;

TRUNCATE TABLE Users;

TRUNCATE TABLE UserMaster;

SET FOREIGN_KEY_CHECKS = 1;

